import { Router } from 'express';
import { validate } from '../../middleware/validate.js';
import { requireAuth } from '../../middleware/auth.js';
import { authRateLimit } from '../../middleware/rateLimit.js';
import * as c from './controller.js';
import { registerSchema, loginSchema } from './schema.js';
import { z } from 'zod';
const router = Router();
router.post('/register', authRateLimit, validate(registerSchema), c.register);
router.post('/login', authRateLimit, validate(loginSchema), c.login);
router.post('/mfa/setup', requireAuth, c.setupMfa);
router.post('/mfa/enable', requireAuth, validate(z.object({ body: z.object({ code: z.string().regex(/^\d{6}$/) }), params: z.object({}), query: z.object({}) })), c.enableMfa);
export default router;
